---
title: "Workshop Overview"
---

The workshop "Machine Learning for Tracking Early Behavior and Environments" will take place on September 16, 2025 as part of the [IEEE International Conference on Learning and Development](https://icdl2025.fel.cvut.cz/) in Prague, Czechia. Drawing 15 speakers with interdisciplinary expertise, the workshop will disseminate cutting-edge applications of machine learning methods in infancy research that span a wide range of topics---perception, sleep, movement, language, emotion, and social interaction. 

The organizers, Sam Wass, John Franchak, and Melina Knabe, invite you to join for the day-long program by registering on the ICDL conference [site](https://icdl2025.fel.cvut.cz/registration/). A morning poster session will provide an opportunity for attendees to discuss ongoing projects. The [logistics page](logistics.qmd) has more details about conference registration and poster submissions.

:::{.callout-tip title="Poster Submissions"}
Poster submissions are encouraged and will be accepted until August 26. Please indicate your interest [here.](https://forms.gle/UKxeYWYwAzEa95Eu7)
:::

## Schedule at a glance

Three talk sessions will demonstrate how researchers use machine learning to assess what infants do (Session 1), what they experience (Session 2), and what they learn (Session 3). See the [detailed program](program.qmd) for speakers and talk abstracts for each session.

| Time | Event | Topic | 
|:-- |:---- |:------ |
| 9:00--10:30   | [Talk Session 1](https://johnfranchak.github.io/icdl_mlcv_workshop_2025/program.html#talk-session-1-using-machine-learning-to-track-behavior)    | Using machine learning to track behavior  | 
| 10:30--11:00  | Coffee break      |                                           |
| 11:00--12:30  | Poster Session    | Attendees present related work            |
| 12:30--14:00  | Lunch | |
| 14:00--15:30  | [Talk Session 2](https://johnfranchak.github.io/icdl_mlcv_workshop_2025/program.html#talk-session-2-using-machine-learning-to-track-environmentsaudio-and-video)    | Using machine learning to track environments---audio and video |
| 15:30--16:00 | Coffee Break | |
| 16:00--17:30 | [Talk Session 3](https://johnfranchak.github.io/icdl_mlcv_workshop_2025/program.html#talk-session-3-using-machine-learning-to-track-learning-through-interactions-with-the-environment) | Using machine learning to track learning through interactions with the environment |

