---
title: "Logistics"
---

<!-- ## Poster instructions -->

<!-- Poster submissions are encouraged and will be accepted until September 1, 2025. Please indicate your interest [here](https://forms.gle/UKxeYWYwAzEa95Eu7). The goal of the poster session is to showcase research related to using machine learning and wearable or environmental sensing technology to study early childhood behavior, environments, and learning. The poster session will be approximately 1.5 hours and provide an opportunity to discuss work with an interdisciplinary audience interested in developmental psychology, machine learning, and robotics. Attendees are welcome to present a poster that will also appear in the main conference as long as it fits the topic. -->

## Registration

All attendees (including presenters) must register for the workshop on the ICDL conference [site](https://icdl2025.fel.cvut.cz/registration/). The registration for the workshop day is a separate fee than the main conference registration. 

## Time and location 

The full-day workshop runs from 9:00 to 17:30. The first session will start promptly at 9:00, so speakers and attendees are encouraged to visit the registration desk early to be sure they are checked in ahead of time. The desk opens at 8:00.

When the room for the workshop is assigned, it will be posted in the ICDL [program](https://icdl2025.fel.cvut.cz/detailed-program/)

## Presenter instructions

Oral presentations will be 14-15 minutes long. Presenters should bring their own laptop and dongles to connect to the projector to show their slides. Speakers should arrive 15 minutes before their session to check their connection. 

Poster presentations should follow the the ICDL [conference guidelines](https://icdl2025.fel.cvut.cz/instructions-for-presenters/).